"use strict";

/**
 * Cleaner Checklist Seeder
 * Seeds default cleaning checklist sections and items
 */

const checklistData = [
  {
    title: "Kitchen",
    icon: "🍳",
    displayOrder: 1,
    items: [
      { content: "Wipe down all countertops", displayOrder: 1 },
      { content: "Clean stovetop and burners - PRO TIP: For tough grease, make a paste with baking soda and water, let sit 15 min, then wipe", displayOrder: 2 },
      { content: "Clean oven exterior and handle", displayOrder: 3 },
      { content: "Clean microwave interior and exterior - PRO TIP: Heat a bowl of water with lemon for 2 min, steam loosens grime for easy wipe", displayOrder: 4 },
      { content: "Wipe down refrigerator exterior and handles - PRO TIP: For stainless steel, always wipe in direction of the grain", displayOrder: 5 },
      { content: "Clean inside refrigerator shelves (if requested)", displayOrder: 6 },
      { content: "Clean dishwasher exterior", displayOrder: 7 },
      { content: "Run dishwasher if full", displayOrder: 8 },
      { content: "Check dishes for cleanliness and put away", displayOrder: 9 },
      { content: "Check silverware for cleanliness", displayOrder: 10 },
      { content: "Wipe down cabinet fronts and handles", displayOrder: 11 },
      { content: "Clean sink and faucet - PRO TIP: Use an old toothbrush around faucet base and handles for hard-to-reach buildup", displayOrder: 12 },
      { content: "Clean garbage disposal - PRO TIP: Run ice cubes with salt and lemon peel to clean blades and freshen", displayOrder: 13 },
      { content: "Empty trash and replace liner", displayOrder: 14 },
      { content: "Take out recycling if full", displayOrder: 15 },
      { content: "Sweep and mop floor", displayOrder: 16 },
      { content: "Wipe down small appliances (toaster, coffee maker, etc.)", displayOrder: 17 },
      { content: "Clean coffee maker and replace filter if needed", displayOrder: 18 },
      { content: "Replace coffee/creamer if provided by homeowner", displayOrder: 19 },
      { content: "Replace paper towels as needed", displayOrder: 20 },
      { content: "Clean backsplash", displayOrder: 21 },
      { content: "Wipe down kitchen table and chairs", displayOrder: 22 },
      { content: "Clean range hood and filter", displayOrder: 23 },
      { content: "Check and organize pantry items (if requested)", displayOrder: 24 },
    ],
  },
  {
    title: "Bathrooms",
    icon: "🚿",
    displayOrder: 2,
    items: [
      { content: "Clean and disinfect toilet (inside bowl, seat, base, and exterior) - PRO TIP: Apply cleaner, let sit 5 min while cleaning other areas, then scrub", displayOrder: 1 },
      { content: "Check toilet bowl for hair and debris, remove", displayOrder: 2 },
      { content: "Clean behind toilet and around base", displayOrder: 3 },
      { content: "Clean toilet brush holder", displayOrder: 4 },
      { content: "Clean sink basin and faucet", displayOrder: 5 },
      { content: "Check sink drain for hair and remove", displayOrder: 6 },
      { content: "Check countertops for hair and remove", displayOrder: 7 },
      { content: "Polish faucet and fixtures to remove water spots", displayOrder: 8 },
      { content: "Clean and disinfect countertops", displayOrder: 9 },
      { content: "Clean mirror (streak-free) - PRO TIP: Wipe with damp paper towel, then immediately dry with dry paper towel using small circles for spotless results", displayOrder: 10 },
      { content: "Clean shower/tub walls and floor", displayOrder: 11 },
      { content: "Check shower drain for hair and remove", displayOrder: 12 },
      { content: "Check tub for hair and remove", displayOrder: 13 },
      { content: "Check shower walls/floor for hair and remove", displayOrder: 14 },
      { content: "Remove soap scum and hard water stains - PRO TIP: White vinegar spray, let sit 10 min, scrub with baking soda for tough buildup", displayOrder: 15 },
      { content: "Clean shower door or curtain (both sides)", displayOrder: 16 },
      { content: "Clean shower head and remove buildup - PRO TIP: Tie a bag of vinegar around shower head overnight for mineral deposits", displayOrder: 17 },
      { content: "Clean shower caddy/organizers", displayOrder: 18 },
      { content: "Clean tub jets (if applicable)", displayOrder: 19 },
      { content: "Wipe down cabinet fronts and handles", displayOrder: 20 },
      { content: "Clean inside medicine cabinet (if requested)", displayOrder: 21 },
      { content: "Clean and organize under-sink area (if requested)", displayOrder: 22 },
      { content: "Clean exhaust fan and vent cover", displayOrder: 23 },
      { content: "Wipe down light fixtures and switches", displayOrder: 24 },
      { content: "Clean towel bars and hooks", displayOrder: 25 },
      { content: "Empty trash and replace liner", displayOrder: 26 },
      { content: "Sweep and mop floor (including corners and behind toilet)", displayOrder: 27 },
      { content: "Check floor for hair and remove", displayOrder: 28 },
      { content: "Clean floor grout (if needed) - PRO TIP: Baking soda paste with hydrogen peroxide, apply to grout, scrub with stiff brush", displayOrder: 29 },
      { content: "Replace hand towels with fresh ones if provided", displayOrder: 30 },
      { content: "Replace bath towels with fresh ones if provided", displayOrder: 31 },
      { content: "Fold or hang towels neatly", displayOrder: 32 },
      { content: "Refill toilet paper (leave extra roll visible)", displayOrder: 33 },
      { content: "Refill hand soap dispenser", displayOrder: 34 },
      { content: "Replace tissues if low", displayOrder: 35 },
      { content: "Check and replace toiletries if provided by homeowner", displayOrder: 36 },
      { content: "Clean scale and bath accessories", displayOrder: 37 },
    ],
  },
  {
    title: "Bedrooms",
    icon: "🛏️",
    displayOrder: 3,
    items: [
      { content: "Strip bed and remake with fresh linens (if provided)", displayOrder: 1 },
      { content: "Fluff and arrange pillows neatly", displayOrder: 2 },
      { content: "Smooth and tuck sheets and blankets", displayOrder: 3 },
      { content: "Check mattress pad for stains (report if needed)", displayOrder: 4 },
      { content: "Dust headboard and bed frame", displayOrder: 5 },
      { content: "Dust nightstands (top, sides, and drawers)", displayOrder: 6 },
      { content: "Clean nightstand surfaces and remove water rings", displayOrder: 7 },
      { content: "Dust and clean lamps and lampshades", displayOrder: 8 },
      { content: "Dust dresser top and mirror", displayOrder: 9 },
      { content: "Clean dresser mirror (streak-free) - use damp then dry paper towel technique", displayOrder: 10 },
      { content: "Dust dresser drawers and handles", displayOrder: 11 },
      { content: "Dust TV and electronics (if present)", displayOrder: 12 },
      { content: "Dust picture frames and wall decor", displayOrder: 13 },
      { content: "Dust window sills and blinds", displayOrder: 14 },
      { content: "Clean windows (interior, if requested)", displayOrder: 15 },
      { content: "Dust ceiling fan blades", displayOrder: 16 },
      { content: "Dust light fixtures and ceiling light", displayOrder: 17 },
      { content: "Wipe down light switches and door handles", displayOrder: 18 },
      { content: "Vacuum carpet thoroughly (include edges)", displayOrder: 19 },
      { content: "Vacuum under bed (if accessible)", displayOrder: 20 },
      { content: "Vacuum closet floor", displayOrder: 21 },
      { content: "Mop hardwood/tile floors", displayOrder: 22 },
      { content: "Spot clean carpet stains (if needed) - PRO TIP: Blot don't rub, use club soda for fresh stains, work from outside in", displayOrder: 23 },
      { content: "Empty trash cans and replace liner", displayOrder: 24 },
      { content: "Organize items on surfaces neatly", displayOrder: 25 },
      { content: "Fold or hang any clothes left out (if requested)", displayOrder: 26 },
      { content: "Check closet organization (if requested)", displayOrder: 27 },
      { content: "Dust baseboards", displayOrder: 28 },
      { content: "Remove cobwebs from corners and ceiling", displayOrder: 29 },
      { content: "Check for and report any damage or maintenance issues", displayOrder: 30 },
    ],
  },
  {
    title: "Living Areas",
    icon: "🛋️",
    displayOrder: 4,
    items: [
      { content: "Dust all furniture surfaces (tables, shelves, stands)", displayOrder: 1 },
      { content: "Dust and polish wood furniture - PRO TIP: Use microfiber cloth, dust first then polish in direction of wood grain", displayOrder: 2 },
      { content: "Clean glass coffee table and end tables (streak-free)", displayOrder: 3 },
      { content: "Dust TV screen carefully with microfiber cloth - PRO TIP: Never use glass cleaner on screens, dry microfiber only", displayOrder: 4 },
      { content: "Dust TV stand and entertainment center", displayOrder: 5 },
      { content: "Dust and organize remote controls", displayOrder: 6 },
      { content: "Dust gaming consoles and electronics", displayOrder: 7 },
      { content: "Dust speakers and audio equipment", displayOrder: 8 },
      { content: "Dust all shelves and bookcases", displayOrder: 9 },
      { content: "Dust books and decorative items", displayOrder: 10 },
      { content: "Dust picture frames and wall art", displayOrder: 11 },
      { content: "Dust mantel and fireplace surround", displayOrder: 12 },
      { content: "Clean fireplace glass (if applicable)", displayOrder: 13 },
      { content: "Vacuum sofa cushions and crevices - PRO TIP: Use rubber glove to gather pet hair before vacuuming", displayOrder: 14 },
      { content: "Vacuum under sofa cushions", displayOrder: 15 },
      { content: "Spot clean upholstery stains", displayOrder: 16 },
      { content: "Fluff and arrange throw pillows", displayOrder: 17 },
      { content: "Fold and arrange throw blankets", displayOrder: 18 },
      { content: "Vacuum chairs and recliners", displayOrder: 19 },
      { content: "Dust lamp bases and clean lampshades", displayOrder: 20 },
      { content: "Dust ceiling fan blades", displayOrder: 21 },
      { content: "Dust blinds and window treatments", displayOrder: 22 },
      { content: "Clean window sills", displayOrder: 23 },
      { content: "Clean interior windows (if requested)", displayOrder: 24 },
      { content: "Vacuum carpet thoroughly (include edges and corners)", displayOrder: 25 },
      { content: "Vacuum area rugs", displayOrder: 26 },
      { content: "Vacuum under furniture (if accessible)", displayOrder: 27 },
      { content: "Mop hardwood/tile floors - PRO TIP: Less water is better for hardwood, damp mop only and dry quickly", displayOrder: 28 },
      { content: "Dust and clean baseboards", displayOrder: 29 },
      { content: "Wipe down light switches and outlet covers", displayOrder: 30 },
      { content: "Dust air vents and registers", displayOrder: 31 },
      { content: "Remove cobwebs from corners and ceiling", displayOrder: 32 },
      { content: "Empty trash cans and replace liner", displayOrder: 33 },
      { content: "Straighten magazines and books on tables", displayOrder: 34 },
      { content: "Water plants (if requested by homeowner)", displayOrder: 35 },
    ],
  },
  {
    title: "Dining Room",
    icon: "🍽️",
    displayOrder: 5,
    items: [
      { content: "Clear and wipe down dining table surface", displayOrder: 1 },
      { content: "Polish wood table (if applicable)", displayOrder: 2 },
      { content: "Clean glass table top (streak-free)", displayOrder: 3 },
      { content: "Check table for crumbs and debris", displayOrder: 4 },
      { content: "Wipe down chair seats and backs", displayOrder: 5 },
      { content: "Dust chair legs and rungs", displayOrder: 6 },
      { content: "Check chairs for food debris and clean", displayOrder: 7 },
      { content: "Dust buffet/sideboard top and sides", displayOrder: 8 },
      { content: "Clean buffet/sideboard hardware and handles", displayOrder: 9 },
      { content: "Dust china cabinet (exterior and glass)", displayOrder: 10 },
      { content: "Clean china cabinet glass (streak-free)", displayOrder: 11 },
      { content: "Dust chandelier or light fixture", displayOrder: 12 },
      { content: "Dust wall sconces", displayOrder: 13 },
      { content: "Dust picture frames and wall decor", displayOrder: 14 },
      { content: "Dust window sills and blinds", displayOrder: 15 },
      { content: "Clean interior windows (if requested)", displayOrder: 16 },
      { content: "Dust baseboards", displayOrder: 17 },
      { content: "Vacuum carpet thoroughly", displayOrder: 18 },
      { content: "Vacuum under dining table and chairs", displayOrder: 19 },
      { content: "Check for and vacuum food crumbs", displayOrder: 20 },
      { content: "Mop hardwood/tile floors", displayOrder: 21 },
      { content: "Vacuum area rug (if present)", displayOrder: 22 },
      { content: "Wipe down light switches", displayOrder: 23 },
      { content: "Straighten table centerpiece", displayOrder: 24 },
      { content: "Replace table linens if provided", displayOrder: 25 },
    ],
  },
  {
    title: "Entryway & Hallways",
    icon: "🚪",
    displayOrder: 6,
    items: [
      { content: "Dust console/entry table top and shelves", displayOrder: 1 },
      { content: "Organize items on entry table neatly", displayOrder: 2 },
      { content: "Clean entry mirror (streak-free) - PRO TIP: Damp paper towel first, then dry immediately with small circles", displayOrder: 3 },
      { content: "Clean hallway mirrors (streak-free) - use damp then dry paper towel technique", displayOrder: 4 },
      { content: "Dust coat rack/hooks", displayOrder: 5 },
      { content: "Straighten shoes and shoe rack", displayOrder: 6 },
      { content: "Wipe down shoe rack/bench", displayOrder: 7 },
      { content: "Clean umbrella stand", displayOrder: 8 },
      { content: "Dust picture frames and wall art", displayOrder: 9 },
      { content: "Dust wall sconces and light fixtures", displayOrder: 10 },
      { content: "Wipe down light switches and outlet covers", displayOrder: 11 },
      { content: "Clean all door handles (front and interior)", displayOrder: 12 },
      { content: "Wipe down door frames and trim", displayOrder: 13 },
      { content: "Clean front door (interior side)", displayOrder: 14 },
      { content: "Clean door glass/windows", displayOrder: 15 },
      { content: "Dust stair railings and banisters", displayOrder: 16 },
      { content: "Wipe down stair railings", displayOrder: 17 },
      { content: "Vacuum stair carpet", displayOrder: 18 },
      { content: "Vacuum stair risers and edges", displayOrder: 19 },
      { content: "Mop hardwood/tile stairs", displayOrder: 20 },
      { content: "Vacuum hallway carpet", displayOrder: 21 },
      { content: "Mop hallway floors", displayOrder: 22 },
      { content: "Vacuum/clean entry mat", displayOrder: 23 },
      { content: "Shake out entry mats outside", displayOrder: 24 },
      { content: "Dust baseboards", displayOrder: 25 },
      { content: "Remove cobwebs from corners and ceiling", displayOrder: 26 },
      { content: "Dust air vents and registers", displayOrder: 27 },
      { content: "Clean closet door handles", displayOrder: 28 },
      { content: "Organize coat closet (if requested)", displayOrder: 29 },
      { content: "Check and replace entry rug if provided", displayOrder: 30 },
    ],
  },
  {
    title: "Home Office",
    icon: "💻",
    displayOrder: 7,
    items: [
      { content: "Clear and wipe down desk surface", displayOrder: 1 },
      { content: "Organize papers and supplies on desk neatly", displayOrder: 2 },
      { content: "Dust desk drawers and handles", displayOrder: 3 },
      { content: "Dust computer monitor screen (microfiber only) - PRO TIP: Power off screen first, dust shows better and prevents static damage", displayOrder: 4 },
      { content: "Dust keyboard (compressed air if available)", displayOrder: 5 },
      { content: "Wipe down mouse and mousepad", displayOrder: 6 },
      { content: "Dust computer tower/laptop exterior", displayOrder: 7 },
      { content: "Dust printer and scanner exterior", displayOrder: 8 },
      { content: "Dust speakers and headphones", displayOrder: 9 },
      { content: "Dust desk lamp and clean shade", displayOrder: 10 },
      { content: "Clean desk lamp base", displayOrder: 11 },
      { content: "Dust all shelves and bookcases", displayOrder: 12 },
      { content: "Dust books and binders", displayOrder: 13 },
      { content: "Organize books and materials neatly", displayOrder: 14 },
      { content: "Dust filing cabinet exterior", displayOrder: 15 },
      { content: "Wipe down filing cabinet handles", displayOrder: 16 },
      { content: "Dust picture frames and diplomas", displayOrder: 17 },
      { content: "Dust wall art and decorations", displayOrder: 18 },
      { content: "Vacuum office chair (fabric)", displayOrder: 19 },
      { content: "Wipe down office chair (leather/vinyl)", displayOrder: 20 },
      { content: "Dust chair base and wheels", displayOrder: 21 },
      { content: "Dust window sills and blinds", displayOrder: 22 },
      { content: "Clean interior windows (if requested)", displayOrder: 23 },
      { content: "Dust ceiling fan blades", displayOrder: 24 },
      { content: "Dust light fixtures", displayOrder: 25 },
      { content: "Wipe down light switches and outlet covers", displayOrder: 26 },
      { content: "Vacuum carpet thoroughly", displayOrder: 27 },
      { content: "Vacuum under desk", displayOrder: 28 },
      { content: "Mop hardwood/tile floors", displayOrder: 29 },
      { content: "Vacuum floor mat/carpet protector", displayOrder: 30 },
      { content: "Dust baseboards", displayOrder: 31 },
      { content: "Empty trash can and replace liner", displayOrder: 32 },
      { content: "Empty paper shredder bin (if requested)", displayOrder: 33 },
      { content: "Remove cobwebs from corners", displayOrder: 34 },
      { content: "Dust air vents and registers", displayOrder: 35 },
    ],
  },
  {
    title: "Laundry Room",
    icon: "🧺",
    displayOrder: 8,
    items: [
      { content: "Wipe down washer exterior and control panel", displayOrder: 1 },
      { content: "Clean washer door seal/gasket - PRO TIP: Wipe with vinegar/water mix to prevent mold, leave door ajar after cleaning", displayOrder: 2 },
      { content: "Check washer drum for debris", displayOrder: 3 },
      { content: "Wipe down dryer exterior and control panel", displayOrder: 4 },
      { content: "Clean lint trap thoroughly - PRO TIP: Wash lint trap monthly with soap to remove dryer sheet residue that blocks airflow", displayOrder: 5 },
      { content: "Check dryer vent for lint buildup", displayOrder: 6 },
      { content: "Wipe inside dryer drum", displayOrder: 7 },
      { content: "Clean laundry sink (if present)", displayOrder: 8 },
      { content: "Wipe down counters/folding area", displayOrder: 9 },
      { content: "Organize laundry supplies neatly", displayOrder: 10 },
      { content: "Wipe down detergent bottles and supplies", displayOrder: 11 },
      { content: "Dust shelving units", displayOrder: 12 },
      { content: "Organize items on shelves", displayOrder: 13 },
      { content: "Wipe down cabinet fronts and handles", displayOrder: 14 },
      { content: "Clean utility sink (if present)", displayOrder: 15 },
      { content: "Dust light fixtures", displayOrder: 16 },
      { content: "Wipe down light switches", displayOrder: 17 },
      { content: "Clean behind washer/dryer (if accessible)", displayOrder: 18 },
      { content: "Sweep floor thoroughly", displayOrder: 19 },
      { content: "Mop floor (including under/around machines)", displayOrder: 20 },
      { content: "Empty trash and replace liner", displayOrder: 21 },
      { content: "Fold and put away clean laundry (if requested)", displayOrder: 22 },
      { content: "Start a load of laundry (if requested)", displayOrder: 23 },
      { content: "Transfer laundry from washer to dryer (if requested)", displayOrder: 24 },
      { content: "Replace laundry supplies as needed (if provided)", displayOrder: 25 },
    ],
  },
  {
    title: "General Tasks",
    icon: "✨",
    displayOrder: 9,
    items: [
      { content: "Dust all ceiling fans (both sides of blades) - PRO TIP: Use a pillowcase to dust blades, traps dust inside so it doesn't fall", displayOrder: 1 },
      { content: "Dust ceiling fan light fixtures", displayOrder: 2 },
      { content: "Dust all blinds thoroughly - PRO TIP: Wear a clean sock on your hand and run fingers along each slat", displayOrder: 3 },
      { content: "Wipe down blinds (if dusty)", displayOrder: 4 },
      { content: "Dust all window sills", displayOrder: 5 },
      { content: "Wipe down window sills", displayOrder: 6 },
      { content: "Clean all interior windows (if requested) - PRO TIP: Damp paper towel, then dry immediately with small circles for spotless glass", displayOrder: 7 },
      { content: "Clean sliding glass doors (both sides if accessible) - use damp then dry technique", displayOrder: 8 },
      { content: "Wipe down all baseboards - PRO TIP: Wipe with dryer sheet after cleaning to repel dust longer", displayOrder: 9 },
      { content: "Spot clean baseboard scuffs", displayOrder: 10 },
      { content: "Vacuum all stairs (carpet)", displayOrder: 11 },
      { content: "Mop all stairs (hardwood/tile)", displayOrder: 12 },
      { content: "Dust stair railings and banisters", displayOrder: 13 },
      { content: "Wipe down stair railings", displayOrder: 14 },
      { content: "Dust all air vents and registers", displayOrder: 15 },
      { content: "Wipe down air vent covers", displayOrder: 16 },
      { content: "Remove all cobwebs (corners, ceilings, doorways) - PRO TIP: Use extendable duster, work top to bottom so debris falls to unclean areas", displayOrder: 17 },
      { content: "Wipe down all door frames and trim", displayOrder: 18 },
      { content: "Clean all light switches", displayOrder: 19 },
      { content: "Clean all outlet covers", displayOrder: 20 },
      { content: "Clean all door handles throughout house", displayOrder: 21 },
      { content: "Dust all light fixtures and chandeliers", displayOrder: 22 },
      { content: "Dust crown molding", displayOrder: 23 },
      { content: "Dust wall art and picture frames throughout", displayOrder: 24 },
      { content: "Dust thermostat", displayOrder: 25 },
      { content: "Dust smoke detectors (exterior only)", displayOrder: 26 },
      { content: "Water plants throughout house (if requested)", displayOrder: 27 },
      { content: "Take out all trash and recyclables", displayOrder: 28 },
      { content: "Replace all trash liners", displayOrder: 29 },
      { content: "Check and replace air fresheners (if provided)", displayOrder: 30 },
      { content: "Spot clean walls for marks and fingerprints", displayOrder: 31 },
      { content: "Check for any pet messes and clean", displayOrder: 32 },
      { content: "Vacuum pet hair from furniture (if applicable) - PRO TIP: Dampen rubber glove and wipe surface to gather hair before vacuuming", displayOrder: 33 },
      { content: "Refill pet water bowls (if requested)", displayOrder: 34 },
    ],
  },
  {
    title: "Final Walkthrough",
    icon: "✅",
    displayOrder: 10,
    items: [
      { content: "Walk through each room and check for missed spots", displayOrder: 1 },
      { content: "Check kitchen counters are clear and clean", displayOrder: 2 },
      { content: "Check bathroom mirrors are streak-free (damp then dry paper towel technique)", displayOrder: 3 },
      { content: "Check all sinks and faucets are polished", displayOrder: 4 },
      { content: "Check toilets are clean and sanitized", displayOrder: 5 },
      { content: "Check all beds are properly made", displayOrder: 6 },
      { content: "Verify floors are clean (no footprints or marks)", displayOrder: 7 },
      { content: "Ensure all trash has been collected and taken out", displayOrder: 8 },
      { content: "Confirm all trash liners have been replaced", displayOrder: 9 },
      { content: "Return all items to their proper places", displayOrder: 10 },
      { content: "Return cleaning supplies to storage location", displayOrder: 11 },
      { content: "Check no cleaning supplies left behind", displayOrder: 12 },
      { content: "Straighten any items moved during cleaning", displayOrder: 13 },
      { content: "Turn off all lights (unless instructed otherwise)", displayOrder: 14 },
      { content: "Close all windows (unless instructed otherwise)", displayOrder: 15 },
      { content: "Check thermostat is set correctly", displayOrder: 16 },
      { content: "Lock all doors if required/instructed", displayOrder: 17 },
      { content: "Set alarm if applicable", displayOrder: 18 },
      { content: "Take before/after photos of key areas", displayOrder: 19 },
      { content: "Take completion photos for documentation", displayOrder: 20 },
      { content: "Note any issues or damage found during cleaning", displayOrder: 21 },
      { content: "Note any items that need replacement", displayOrder: 22 },
      { content: "Note any maintenance issues observed", displayOrder: 23 },
      { content: "Leave welcome note/card if provided", displayOrder: 24 },
      { content: "Final smell check (ensure home smells fresh)", displayOrder: 25 },
      { content: "Check for any personal items left by previous cleaner", displayOrder: 26 },
      { content: "Confirm job completion in app", displayOrder: 27 },
    ],
  },
];

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const now = new Date();

    // First, check if data already exists to avoid duplicates
    const existingSections = await queryInterface.sequelize.query(
      'SELECT COUNT(*) as count FROM "ChecklistSections"',
      { type: Sequelize.QueryTypes.SELECT }
    );

    if (existingSections[0].count > 0) {
      console.log("Checklist data already exists, skipping seeder...");
      return;
    }

    // Insert sections and their items
    for (const section of checklistData) {
      // Insert section
      const [sectionResult] = await queryInterface.sequelize.query(
        `INSERT INTO "ChecklistSections" (title, icon, "displayOrder", "createdAt", "updatedAt")
         VALUES (:title, :icon, :displayOrder, :createdAt, :updatedAt)
         RETURNING id`,
        {
          replacements: {
            title: section.title,
            icon: section.icon,
            displayOrder: section.displayOrder,
            createdAt: now,
            updatedAt: now,
          },
          type: Sequelize.QueryTypes.INSERT,
        }
      );

      const sectionId = sectionResult[0].id;

      // Insert items for this section
      for (const item of section.items) {
        await queryInterface.sequelize.query(
          `INSERT INTO "ChecklistItems" ("sectionId", "parentId", content, "displayOrder", "indentLevel", formatting, "isActive", "createdAt", "updatedAt")
           VALUES (:sectionId, NULL, :content, :displayOrder, 0, :formatting, true, :createdAt, :updatedAt)`,
          {
            replacements: {
              sectionId: sectionId,
              content: item.content,
              displayOrder: item.displayOrder,
              formatting: JSON.stringify({ bold: false, italic: false, bulletStyle: "disc" }),
              createdAt: now,
              updatedAt: now,
            },
            type: Sequelize.QueryTypes.INSERT,
          }
        );
      }
    }

    console.log("Cleaner checklist seeded successfully!");
  },

  down: async (queryInterface, Sequelize) => {
    // Delete all checklist items first (foreign key constraint)
    await queryInterface.bulkDelete("ChecklistItems", null, {});
    // Then delete all sections
    await queryInterface.bulkDelete("ChecklistSections", null, {});
    console.log("Cleaner checklist data removed.");
  },
};
