const express = require("express");
const clientRouter = require("./clientRouter");
const userSessionsRouter = require("./api/v1/userSessionsRouter");
const usersRouter = require("./api/v1/usersRouter");
const userInfoRouter = require("./api/v1/userInfoRouter");
const appointmentRouter = require("./api/v1/appointmentsRouter");
const employeeInfoRouter = require("./api/v1/employeeInfoRouter");
const applicationRouter = require("./api/v1/applicationRouter");
const reviewsRouter = require("./api/v1/reviewsRouter");
const paymentRouter = require("./api/v1/paymentRouter");
const messageRouter = require("./api/v1/messageRouter");
const stripeConnectRouter = require("./api/v1/stripeConnectRouter");
const taxRouter = require("./api/v1/taxRouter");
const jobPhotosRouter = require("./api/v1/jobPhotosRouter");
const calendarSyncRouter = require("./api/v1/calendarSyncRouter");
const ownerDashboardRouter = require("./api/v1/ownerDashboardRouter");
const hrDashboardRouter = require("./api/v1/hrDashboardRouter");
const termsRouter = require("./api/v1/termsRouter");
const pricingRouter = require("./api/v1/pricingRouter");
const incentivesRouter = require("./api/v1/incentivesRouter");
const pushNotificationRouter = require("./api/v1/pushNotificationRouter");
const homeSizeAdjustmentRouter = require("./api/v1/homeSizeAdjustmentRouter");
const checklistRouter = require("./api/v1/checklistRouter");
const referralRouter = require("./api/v1/referralRouter");
const cleanerClientsRouter = require("./api/v1/cleanerClientsRouter");
const recurringSchedulesRouter = require("./api/v1/recurringSchedulesRouter");
const billingRouter = require("./api/v1/billingRouter");
const preferredCleanerRouter = require("./api/v1/preferredCleanerRouter");
const suspiciousReportsRouter = require("./api/v1/suspiciousReportsRouter");
const notificationsRouter = require("./api/v1/notificationsRouter");
const multiCleanerRouter = require("./api/v1/multiCleanerRouter");
const businessOwnerRouter = require("./api/v1/businessOwnerRouter");
const businessEmployeeRouter = require("./api/v1/businessEmployeeRouter");
const completionRouter = require("./api/v1/completionRouter");

const rootRouter = new express.Router();

rootRouter.use("/api/v1/user-sessions", userSessionsRouter);
rootRouter.use("/api/v1/users", usersRouter);
rootRouter.use("/api/v1/user-info", userInfoRouter);
rootRouter.use("/api/v1/employee-info", employeeInfoRouter);
rootRouter.use("/api/v1/appointments", appointmentRouter);
rootRouter.use("/api/v1/applications", applicationRouter);
rootRouter.use("/api/v1/reviews", reviewsRouter);
rootRouter.use("/api/v1/payments", paymentRouter);
rootRouter.use("/api/v1/messages", messageRouter);
rootRouter.use("/api/v1/stripe-connect", stripeConnectRouter);
rootRouter.use("/api/v1/tax", taxRouter);
rootRouter.use("/api/v1/job-photos", jobPhotosRouter);
rootRouter.use("/api/v1/calendar-sync", calendarSyncRouter);
rootRouter.use("/api/v1/owner-dashboard", ownerDashboardRouter);
rootRouter.use("/api/v1/hr-dashboard", hrDashboardRouter);
rootRouter.use("/api/v1/terms", termsRouter);
rootRouter.use("/api/v1/pricing", pricingRouter);
rootRouter.use("/api/v1/incentives", incentivesRouter);
rootRouter.use("/api/v1/push-notifications", pushNotificationRouter);
rootRouter.use("/api/v1/home-size-adjustment", homeSizeAdjustmentRouter);
rootRouter.use("/api/v1/checklist", checklistRouter);
rootRouter.use("/api/v1/referrals", referralRouter);
rootRouter.use("/api/v1/cleaner-clients", cleanerClientsRouter);
rootRouter.use("/api/v1/recurring-schedules", recurringSchedulesRouter);
rootRouter.use("/api/v1/billing", billingRouter);
rootRouter.use("/api/v1/preferred-cleaner", preferredCleanerRouter);
rootRouter.use("/api/v1/suspicious-reports", suspiciousReportsRouter);
rootRouter.use("/api/v1/notifications", notificationsRouter);
rootRouter.use("/api/v1/multi-cleaner", multiCleanerRouter);
rootRouter.use("/api/v1/business-owner", businessOwnerRouter);
rootRouter.use("/api/v1/business-employee", businessEmployeeRouter);
rootRouter.use("/api/v1/completion", completionRouter);

rootRouter.use("/", clientRouter);

module.exports = rootRouter;
