const EncryptionService = require("../services/EncryptionService");

class MultiCleanerJobSerializer {
	static userEncryptedFields = ["firstName", "lastName", "email", "phone"];

	static decryptUserField(value) {
		if (!value) return null;
		return EncryptionService.decrypt(value);
	}

	static serializeUser(user) {
		if (!user) return null;
		const data = user.dataValues || user;
		return {
			id: data.id,
			firstName: this.decryptUserField(data.firstName),
			lastName: this.decryptUserField(data.lastName),
			type: data.type
		};
	}

	static serializeOne(job) {
		const data = job.dataValues || job;

		const serialized = {
			id: data.id,
			appointmentId: data.appointmentId,
			totalCleanersRequired: data.totalCleanersRequired,
			cleanersConfirmed: data.cleanersConfirmed,
			status: data.status,
			primaryCleanerId: data.primaryCleanerId,
			isAutoGenerated: data.isAutoGenerated,
			totalEstimatedMinutes: data.totalEstimatedMinutes,
			openedToMarketAt: data.openedToMarketAt,
			filledAt: data.filledAt,
			urgentNotificationSentAt: data.urgentNotificationSentAt,
			finalWarningAt: data.finalWarningAt,
			createdAt: data.createdAt,
			updatedAt: data.updatedAt
		};

		// Computed properties
		serialized.isFilled = data.cleanersConfirmed >= data.totalCleanersRequired;
		serialized.remainingSlots = Math.max(0, data.totalCleanersRequired - data.cleanersConfirmed);

		// Serialize primary cleaner if included
		if (job.primaryCleaner) {
			serialized.primaryCleaner = this.serializeUser(job.primaryCleaner);
		}

		// Serialize room assignments if included
		if (job.roomAssignments) {
			serialized.roomAssignments = job.roomAssignments.map(assignment =>
				this.serializeRoomAssignment(assignment)
			);
		}

		// Serialize offers if included
		if (job.offers) {
			serialized.offers = job.offers.map(offer =>
				this.serializeOffer(offer)
			);
		}

		// Serialize completions if included
		if (job.completions) {
			serialized.completions = job.completions.map(completion =>
				this.serializeCompletion(completion)
			);
		}

		return serialized;
	}

	static serializeArray(jobs) {
		return jobs.map((job) => this.serializeOne(job));
	}

	static serializeRoomAssignment(assignment) {
		const data = assignment.dataValues || assignment;

		const serialized = {
			id: data.id,
			multiCleanerJobId: data.multiCleanerJobId,
			cleanerId: data.cleanerId,
			rooms: data.rooms,
			estimatedMinutes: data.estimatedMinutes,
			status: data.status,
			startedAt: data.startedAt,
			completedAt: data.completedAt,
			createdAt: data.createdAt
		};

		// Serialize cleaner if included
		if (assignment.cleaner) {
			serialized.cleaner = this.serializeUser(assignment.cleaner);
		}

		return serialized;
	}

	static serializeOffer(offer) {
		const data = offer.dataValues || offer;

		return {
			id: data.id,
			multiCleanerJobId: data.multiCleanerJobId,
			cleanerId: data.cleanerId,
			status: data.status,
			offeredAt: data.offeredAt,
			respondedAt: data.respondedAt,
			expiresAt: data.expiresAt,
			createdAt: data.createdAt
		};
	}

	static serializeCompletion(completion) {
		const data = completion.dataValues || completion;

		return {
			id: data.id,
			multiCleanerJobId: data.multiCleanerJobId,
			cleanerId: data.cleanerId,
			completedAt: data.completedAt,
			notes: data.notes,
			createdAt: data.createdAt
		};
	}

	static serializeForList(job) {
		const data = job.dataValues || job;

		return {
			id: data.id,
			appointmentId: data.appointmentId,
			totalCleanersRequired: data.totalCleanersRequired,
			cleanersConfirmed: data.cleanersConfirmed,
			status: data.status,
			isFilled: data.cleanersConfirmed >= data.totalCleanersRequired,
			remainingSlots: Math.max(0, data.totalCleanersRequired - data.cleanersConfirmed)
		};
	}

	static serializeArrayForList(jobs) {
		return jobs.map((job) => this.serializeForList(job));
	}
}

module.exports = MultiCleanerJobSerializer;
