const EncryptionService = require("../services/EncryptionService");

class MultiCleanerJobSerializer {
	static userEncryptedFields = ["firstName", "lastName", "email", "phone"];

	// Home fields that are encrypted
	static homeEncryptedFields = [
		"address",
		"city",
		"state",
		"zipcode",
		"keyPadCode",
		"keyLocation",
		"contact",
		"gateCode",
		"accessNotes",
	];

	static decryptField(value) {
		if (!value) return null;
		return EncryptionService.decrypt(value);
	}

	static decryptUserField(value) {
		if (!value) return null;
		return EncryptionService.decrypt(value);
	}

	static serializeUser(user) {
		if (!user) return null;
		const data = user.dataValues || user;
		return {
			id: data.id,
			firstName: this.decryptUserField(data.firstName),
			lastName: this.decryptUserField(data.lastName),
			type: data.type
		};
	}

	static serializeHome(home) {
		if (!home) return null;
		const data = home.dataValues || home;
		return {
			id: data.id,
			nickName: data.nickName,
			address: this.decryptField(data.address),
			city: this.decryptField(data.city),
			state: this.decryptField(data.state),
			zipcode: this.decryptField(data.zipcode),
			numBeds: data.numBeds,
			numBaths: data.numBaths,
			numHalfBaths: data.numHalfBaths,
			sqft: data.sqft,
			hasGate: data.hasGate,
			gateCode: this.decryptField(data.gateCode),
			hasDog: data.hasDog,
			dogName: data.dogName,
			hasCat: data.hasCat,
			catName: data.catName,
			accessNotes: this.decryptField(data.accessNotes),
			contact: this.decryptField(data.contact),
			timeToBeCompleted: data.timeToBeCompleted,
			cleanersNeeded: data.cleanersNeeded,
		};
	}

	static serializeAppointment(appointment) {
		if (!appointment) return null;
		const data = appointment.dataValues || appointment;
		return {
			id: data.id,
			date: data.date,
			price: data.price,
			bringTowels: data.bringTowels,
			bringSheets: data.bringSheets,
			timeToBeCompleted: data.timeToBeCompleted,
			completed: data.completed,
			isMultiCleanerJob: data.isMultiCleanerJob,
			home: appointment.home ? this.serializeHome(appointment.home) : null,
		};
	}

	static serializeOne(job) {
		const data = job.dataValues || job;

		const serialized = {
			id: data.id,
			appointmentId: data.appointmentId,
			totalCleanersRequired: data.totalCleanersRequired,
			cleanersConfirmed: data.cleanersConfirmed,
			status: data.status,
			primaryCleanerId: data.primaryCleanerId,
			isAutoGenerated: data.isAutoGenerated,
			totalEstimatedMinutes: data.totalEstimatedMinutes,
			openedToMarketAt: data.openedToMarketAt,
			filledAt: data.filledAt,
			urgentNotificationSentAt: data.urgentNotificationSentAt,
			finalWarningAt: data.finalWarningAt,
			createdAt: data.createdAt,
			updatedAt: data.updatedAt
		};

		// Computed properties
		serialized.isFilled = data.cleanersConfirmed >= data.totalCleanersRequired;
		serialized.remainingSlots = Math.max(0, data.totalCleanersRequired - data.cleanersConfirmed);

		// Serialize primary cleaner if included
		if (job.primaryCleaner) {
			serialized.primaryCleaner = this.serializeUser(job.primaryCleaner);
		}

		// Serialize room assignments if included
		if (job.roomAssignments) {
			serialized.roomAssignments = job.roomAssignments.map(assignment =>
				this.serializeRoomAssignment(assignment)
			);
		}

		// Serialize offers if included
		if (job.offers) {
			serialized.offers = job.offers.map(offer =>
				this.serializeOffer(offer)
			);
		}

		// Serialize completions if included
		if (job.completions) {
			serialized.completions = job.completions.map(completion =>
				this.serializeCompletion(completion)
			);
		}

		// Serialize appointment if included
		if (job.appointment) {
			serialized.appointment = this.serializeAppointment(job.appointment);
		}

		return serialized;
	}

	static serializeArray(jobs) {
		return jobs.map((job) => this.serializeOne(job));
	}

	static serializeRoomAssignment(assignment) {
		const data = assignment.dataValues || assignment;

		const serialized = {
			id: data.id,
			multiCleanerJobId: data.multiCleanerJobId,
			cleanerId: data.cleanerId,
			rooms: data.rooms,
			estimatedMinutes: data.estimatedMinutes,
			status: data.status,
			startedAt: data.startedAt,
			completedAt: data.completedAt,
			createdAt: data.createdAt
		};

		// Serialize cleaner if included
		if (assignment.cleaner) {
			serialized.cleaner = this.serializeUser(assignment.cleaner);
		}

		return serialized;
	}

	static serializeOffer(offer) {
		const data = offer.dataValues || offer;

		const serialized = {
			id: data.id,
			multiCleanerJobId: data.multiCleanerJobId,
			cleanerId: data.cleanerId,
			appointmentId: data.appointmentId,
			offerType: data.offerType,
			status: data.status,
			earningsOffered: data.earningsOffered,
			roomsOffered: data.roomsOffered,
			offeredAt: data.offeredAt,
			respondedAt: data.respondedAt,
			expiresAt: data.expiresAt,
			createdAt: data.createdAt
		};

		// Serialize multiCleanerJob if included (with nested appointment/home)
		if (offer.multiCleanerJob) {
			serialized.multiCleanerJob = this.serializeOne(offer.multiCleanerJob);
		}

		return serialized;
	}

	static serializeCompletion(completion) {
		const data = completion.dataValues || completion;

		return {
			id: data.id,
			multiCleanerJobId: data.multiCleanerJobId,
			cleanerId: data.cleanerId,
			completedAt: data.completedAt,
			notes: data.notes,
			createdAt: data.createdAt
		};
	}

	static serializeForList(job) {
		const data = job.dataValues || job;

		return {
			id: data.id,
			appointmentId: data.appointmentId,
			totalCleanersRequired: data.totalCleanersRequired,
			cleanersConfirmed: data.cleanersConfirmed,
			status: data.status,
			isFilled: data.cleanersConfirmed >= data.totalCleanersRequired,
			remainingSlots: Math.max(0, data.totalCleanersRequired - data.cleanersConfirmed)
		};
	}

	static serializeArrayForList(jobs) {
		return jobs.map((job) => this.serializeForList(job));
	}

	static serializeOfferArray(offers) {
		return offers.map((offer) => this.serializeOffer(offer));
	}

	/**
	 * Serialize offers response for the /offers endpoint
	 * Includes both personal offers and available jobs with decrypted home data
	 */
	static serializeOffersResponse(personalOffers, availableJobs) {
		return {
			personalOffers: this.serializeOfferArray(personalOffers),
			availableJobs: this.serializeArray(availableJobs),
		};
	}
}

module.exports = MultiCleanerJobSerializer;
